<?php
	$title = 'Create order';
	$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<form method="post" action="/order/createOrder">
	<table class="table">
	<thead>
		<tr>
			<th>id</th>
			<th>name</th>
			<th>in stock</th>
			<th>buy</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($items as $o):?>
		<tr>
			<td>
			<input type="checkbox" name="item[]" value="<?php echo $o->getId();?>" />
			<?php echo $o->getId();?></td>
			<td><?php echo $o->getName();?></td>
			<td><?php echo $o->getCount();?></td>
			<td><input class="input-small" type="number" name="itemCount_<?php echo $o->getId();?>" value="1" /></td>
		</tr>
		<?php endforeach;?>
	</tbody>
	</table>
	
	<button type="submit" class="btn btn-success">Create order</button>
	<a href="/order" class="btn">Cancel</a>

</form>