<h3>Traffic</h3>

<div class="mainMenu">

<div class="header">
Header1
</div>
<div class="content">
	<ul>
		<li><a href="">Menu1</a></li>	
		<li><a href="">Menu2</a></li>
		<li><a href="">Menu3</a></li>
	</ul>
</div>

<div class="header">
Header2
</div>
<div class="content">
	<ul>
		<li><a href="">Menu1</a></li>	
		<li><a href="">Menu2</a></li>
		<li><a href="">Menu3</a></li>
	</ul>
</div>



</div>



<?php 
	if ($role == 'admin') :
	
	
	
	
	
	endif;
?>

<script>
(function(){
	$(".mainMenu .content").hide();
	$(".mainMenu .header").on('click', function() {


		});
})();



</script>