<?php
	$title = 'Маршруты';
	$this->headTitle($title);
?>

<div id="rightHolder"></div>

<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<?php 
if ($error) {
		echo "<div class='alert alert-error'>$error</div>";
	}
if ($success) {
		echo "<div class='alert alert-success'>$success</div>";
	}
?>

<table class="table table-hover table-bordered" style="width:55%;">
<thead>
<tr>
	<th style="width:25%"># маршрута</th>
	<th>Описание</th>
</tr></thead>
<tbody>
	<?php foreach ($routes as $r):?>
	<tr class="clickable" id="it_<?php echo $r->getId();?>">
		<td><?php echo $r->getId();?></td>
		<td><?php echo $r->getDescriptionNormal();?></td>
	</tr>
	<?php endforeach;?>
</tbody>
</table>

<a href="<?php echo $this->url('home/cargo', array('action'=>'createPath'));?>" class="btn btn-success">Добавить</a>
<a href="#" id="editPath" disabled="disabled" class="btn btn-warning">Редактировать</a>
<a href="#" id="deletePath" disabled="disabled" class="btn btn-danger">Удалить</a>
<a href="<?php echo $this->url('home');?>" class="btn">Отмена</a>

<script>
	
(function(){
	$('.clickable').click(function(){
		$(this).css({'font-weight':'bold', 'color':'navy'}).siblings().css({'font-weight':'normal', 'color':'black'});
		var id = $(this).attr('id').split('_');
		$('#editPath').attr({'href':'<?php echo $this->url('home/cargo', array('action'=>'updatePath'));?>/'+id[1]});
		$('#deletePath').attr({'href':'<?php echo $this->url('home/cargo', array('action'=>'deletePath'));?>'+id[1]});
		$('#editPath, #deletePath').removeAttr('disabled');
		$.post('<?php echo $this->url('home/cargo', array('action'=>'getPathContent'));?>/'+id[1], {}, function(data) {
			$('#rightHolder').html(data);
			})
		});
})();

</script>

