<?php
	$title = 'Добавление пользователя';
	$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('home/users', array('action' => 'createUser')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
	echo $this->formHidden($form->get('id'));
	
	if ($error) echo "<div class=\"alert alert-error\">$error</div>";
	
	echo $this->formLabel($form->get('fullName'));
	echo $this->formText($form->get('fullName'));
	echo $this->formElementErrors($form->get('fullName'), array('class' => 'alert alert-warning'));
	
	echo "<br>";

	echo $this->formLabel($form->get('username'));
	echo $this->formText($form->get('username'));
	echo $this->formElementErrors($form->get('username'), array('class' => 'alert alert-warning'));
	
	echo "<br>";
	
	echo $this->formLabel($form->get('password'));
	echo $this->formPassword($form->get('password'));
	echo $this->formElementErrors($form->get('password'), array('class' => 'alert alert-warning'));
	
	echo "<br>";
	
	echo $this->formLabel($form->get('role'));
	echo $this->formSelect($form->get('role'));
	
	echo "<br>";
	
	echo $this->formHidden($form->get('csrf'));
	
	echo $this->formElement($form->get('submit'));
	echo " <a href='/' class='btn'>Отмена</a>";
	echo $this->form()->closeTag();
	
?>

