<?php
	$title = 'Add new user';
	$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('home/users', array('action' => 'createUser')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('fullName'));
	echo $this->formRow($form->get('username'));
	echo $this->formRow($form->get('password'));
	
	echo $this->formHidden($form->get('csrf'));
	echo $this->formElement($form->get('submit'));
	echo $this->form()->closeTag();
	
?>

