<?php
	$title = 'Login';
	$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<?php

	if ($failure) {
		echo "<h4>Incorrect username / password.</h4>";
	}

	$form = $this->form;
	$form->setAttribute('action', $this->url('home/security', array('action' => 'index')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
	echo $this->formRow($form->get('username'));
	echo $this->formRow($form->get('password'));
	
	echo $this->formHidden($form->get('csrf'));
	echo $this->formElement($form->get('submit'));
	echo $this->form()->closeTag();
	
?>

