<?php
	$title = 'Add new item';
	$this->headTitle($title);
?>
<h3>
	<?php echo $this->escapeHtml($title); ?>
</h3>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('home/orders', array('action' => 'createItem')));
	$form->prepare();
	
	echo $this->form()->openTag($form);
	
	echo $this->formHidden($form->get('id'));
	echo $this->formRow($form->get('name'));
	echo $this->formRow($form->get('count'));
	
	echo $this->formHidden($form->get('csrf'));
	echo $this->formElement($form->get('submit'));
	echo $this->form()->closeTag();
	
?>

