<h3>Items in order #<?php echo $orderId;?></h3>
<table class="table table-bordered" style="width:100%;">
<thead>
<tr>
	<th>id</th>
	<th>name</th>
	<th>count</th>
</tr></thead>
<tbody>
	<?php foreach ($items as $o):?>
	<tr>
		<td><?php echo $o->getItem()->getId();?></td>
		<td><?php echo $o->getItem()->getName();?></td>
		<td><?php echo $o->getCount();?></td>
	</tr>
	<?php endforeach;?>
</tbody>
</table>