<div id="rightHolder"></div>
<h3>Orders:</h3>
<table class="table table-hover table-bordered" style="width:55%;">
<thead>
<tr>
	<th>id</th>
	<th># items</th>
</tr></thead>
<tbody>
	<?php foreach ($orders as $o):?>
	<tr class="clickable" id="it_<?php echo $o->getId();?>">
		<td><?php echo $o->getId();?></td>
		<td><?php echo count($o->getItems());?></td>
	</tr>
	<?php endforeach;?>
</tbody>
</table>

<a class="btn" href="/order/createOrder">
Create order</a>

<script type="text/javascript">

$(document).ready(function(){
	$('.clickable').click(function(){
		var id = $(this).attr('id').split('_');
		$.post('/order/getItems/'+id[1], {}, function(data) {
			$('#rightHolder').html(data);
			})
		});
});

</script>